---
host: https://10.42.2.241
user: admin
pass: adm!nd42

# '%s' placehold is REQUIRED as the generic filter.  otherwise, write whatever query you like
# query: SELECT * from view_device_v1 WHERE name = '%s' 
# query: SELECT *, (SELECT value FROM view_device_custom_fields_v1 WHERE device_name = '{nodename}') FROM view_device_v1 WHERE name = '{nodename}' 

query: SELECT *, ( SELECT value FROM view_device_custom_fields_v1 WHERE device_fk = device_pk AND key = 'Salt Node ID') AS "salt_node_id" FROM view_device_v1 WHERE name = '{nodename}' 

# query: SELECT *, '{subqueries}' FROM view_device_v1 WHERE name = '{nodename}'


# it is a good idea to alias your custom fields to names with no spaces, so Salt Node ID should alias as Salt_Node_ID 

custom_fields_to_get:
  - test_field: test_field 
  - Salt Node ID: salt_node_id 

# very simple method to get fields ONLY from the main view_device_v1 table 
fields_to_get:
  - name
  - os_name
  - os_version
  - service_level
  - tags
